#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lzo
Version  : 2.09
Release  : 11
URL      : http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz
Source0  : http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: lzo-lib
Requires: lzo-doc

%description
============================================================================
LZO -- a real-time data compression library
============================================================================

%package dev
Summary: dev components for the lzo package.
Group: Development
Requires: lzo-lib

%description dev
dev components for the lzo package.


%package doc
Summary: doc components for the lzo package.
Group: Documentation

%description doc
doc components for the lzo package.


%package lib
Summary: lib components for the lzo package.
Group: Libraries

%description lib
lib components for the lzo package.


%prep
%setup -q -n lzo-2.09

%build
%configure --disable-static --enable-shared
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make test

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/lzo/lzo1.h
/usr/include/lzo/lzo1a.h
/usr/include/lzo/lzo1b.h
/usr/include/lzo/lzo1c.h
/usr/include/lzo/lzo1f.h
/usr/include/lzo/lzo1x.h
/usr/include/lzo/lzo1y.h
/usr/include/lzo/lzo1z.h
/usr/include/lzo/lzo2a.h
/usr/include/lzo/lzo_asm.h
/usr/include/lzo/lzoconf.h
/usr/include/lzo/lzodefs.h
/usr/include/lzo/lzoutil.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/lzo/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
